const Instruction = @import("instruction.zig");

pub const InstructionTable = [256]?Instruction{
    // 0x00
    .{ .op = .brk, .mode = .imp, .cycles = 7 },
    .{ .op = .ora, .mode = .izx, .cycles = 6 },
    null,
    null,
    null,
    .{ .op = .ora, .mode = .zp, .cycles = 3 },
    .{ .op = .asl, .mode = .zp, .cycles = 5 },
    null,
    .{ .op = .php, .mode = .imp, .cycles = 3 },
    .{ .op = .ora, .mode = .imm, .cycles = 2 },
    .{ .op = .asl, .mode = .acc, .cycles = 2 },
    null,
    null,
    .{ .op = .ora, .mode = .abs, .cycles = 4 },
    .{ .op = .asl, .mode = .abs, .cycles = 6 },
    null,

    // 0x10
    .{ .op = .bpl, .mode = .rel, .cycles = 2 },
    .{ .op = .ora, .mode = .izy, .cycles = 5, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .ora, .mode = .zpx, .cycles = 4 },
    .{ .op = .asl, .mode = .zpx, .cycles = 6 },
    null,
    .{ .op = .clc, .mode = .imp, .cycles = 2 },
    .{ .op = .ora, .mode = .aby, .cycles = 4, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .ora, .mode = .abx, .cycles = 4, .page_cycle = true },
    .{ .op = .asl, .mode = .abx, .cycles = 7 },
    null,

    // 0x20
    .{ .op = .jsr, .mode = .abs, .cycles = 6 },
    .{ .op = .@"and", .mode = .izx, .cycles = 6 },
    null,
    null,
    .{ .op = .bit, .mode = .zp, .cycles = 3 },
    .{ .op = .@"and", .mode = .zp, .cycles = 3 },
    .{ .op = .rol, .mode = .zp, .cycles = 5 },
    null,
    .{ .op = .plp, .mode = .imp, .cycles = 4 },
    .{ .op = .@"and", .mode = .imm, .cycles = 2 },
    .{ .op = .rol, .mode = .acc, .cycles = 2 },
    null,
    .{ .op = .bit, .mode = .abs, .cycles = 4 },
    .{ .op = .@"and", .mode = .abs, .cycles = 4 },
    .{ .op = .rol, .mode = .abs, .cycles = 6 },
    null,

    // 0x30
    .{ .op = .bmi, .mode = .rel, .cycles = 2 },
    .{ .op = .@"and", .mode = .izy, .cycles = 5, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .@"and", .mode = .zpx, .cycles = 4 },
    .{ .op = .rol, .mode = .zpx, .cycles = 6 },
    null,
    .{ .op = .sec, .mode = .imp, .cycles = 2 },
    .{ .op = .@"and", .mode = .aby, .cycles = 4, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .@"and", .mode = .abx, .cycles = 4, .page_cycle = true },
    .{ .op = .rol, .mode = .abx, .cycles = 7 },
    null,

    // 0x40
    .{ .op = .rti, .mode = .imp, .cycles = 6 },
    .{ .op = .eor, .mode = .izx, .cycles = 6 },
    null,
    null,
    null,
    .{ .op = .eor, .mode = .zp, .cycles = 3 },
    .{ .op = .lsr, .mode = .zp, .cycles = 5 },
    null,
    .{ .op = .pha, .mode = .imp, .cycles = 3 },
    .{ .op = .eor, .mode = .imm, .cycles = 2 },
    .{ .op = .lsr, .mode = .acc, .cycles = 2 },
    null,
    .{ .op = .jmp, .mode = .abs, .cycles = 3 },
    .{ .op = .eor, .mode = .abs, .cycles = 4 },
    .{ .op = .lsr, .mode = .abs, .cycles = 6 },
    null,

    // 0x50
    .{ .op = .bvc, .mode = .rel, .cycles = 2 },
    .{ .op = .eor, .mode = .izy, .cycles = 5, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .eor, .mode = .zpx, .cycles = 4 },
    .{ .op = .lsr, .mode = .zpx, .cycles = 6 },
    null,
    .{ .op = .cli, .mode = .imp, .cycles = 2 },
    .{ .op = .eor, .mode = .aby, .cycles = 4, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .eor, .mode = .abx, .cycles = 4, .page_cycle = true },
    .{ .op = .lsr, .mode = .abx, .cycles = 7 },
    null,

    // 0x60
    .{ .op = .rts, .mode = .imp, .cycles = 6 },
    .{ .op = .adc, .mode = .izx, .cycles = 6 },
    null,
    null,
    null,
    .{ .op = .adc, .mode = .zp, .cycles = 3 },
    .{ .op = .ror, .mode = .zp, .cycles = 5 },
    null,
    .{ .op = .pla, .mode = .imp, .cycles = 4 },
    .{ .op = .adc, .mode = .imm, .cycles = 2 },
    .{ .op = .ror, .mode = .acc, .cycles = 2 },
    null,
    .{ .op = .jmp, .mode = .ind, .cycles = 5 },
    .{ .op = .adc, .mode = .abs, .cycles = 4 },
    .{ .op = .ror, .mode = .abs, .cycles = 6 },
    null,

    // 0x70
    .{ .op = .bvs, .mode = .rel, .cycles = 2 },
    .{ .op = .adc, .mode = .izy, .cycles = 5, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .adc, .mode = .zpx, .cycles = 4 },
    .{ .op = .ror, .mode = .zpx, .cycles = 6 },
    null,
    .{ .op = .sei, .mode = .imp, .cycles = 2 },
    .{ .op = .adc, .mode = .aby, .cycles = 4, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .adc, .mode = .abx, .cycles = 4, .page_cycle = true },
    .{ .op = .ror, .mode = .abx, .cycles = 7 },
    null,

    // 0x80
    null,
    .{ .op = .sta, .mode = .izx, .cycles = 6 },
    null,
    null,
    .{ .op = .sty, .mode = .zp, .cycles = 3 },
    .{ .op = .sta, .mode = .zp, .cycles = 3 },
    .{ .op = .stx, .mode = .zp, .cycles = 3 },
    null,
    .{ .op = .dey, .mode = .imp, .cycles = 2 },
    null,
    .{ .op = .txa, .mode = .imp, .cycles = 2 },
    null,
    .{ .op = .sty, .mode = .abs, .cycles = 4 },
    .{ .op = .sta, .mode = .abs, .cycles = 4 },
    .{ .op = .stx, .mode = .abs, .cycles = 4 },
    null,

    // 0x90
    .{ .op = .bcc, .mode = .rel, .cycles = 2 },
    .{ .op = .sta, .mode = .izy, .cycles = 6 },
    null,
    null,
    .{ .op = .sty, .mode = .zpx, .cycles = 4 },
    .{ .op = .sta, .mode = .zpx, .cycles = 4 },
    .{ .op = .stx, .mode = .zpy, .cycles = 4 },
    null,
    .{ .op = .tya, .mode = .imp, .cycles = 2 },
    .{ .op = .sta, .mode = .aby, .cycles = 5 },
    .{ .op = .txs, .mode = .imp, .cycles = 2 },
    null,
    null,
    .{ .op = .sta, .mode = .abx, .cycles = 5 },
    null,
    null,

    // 0xa0
    .{ .op = .ldy, .mode = .imm, .cycles = 2 },
    .{ .op = .lda, .mode = .izx, .cycles = 6 },
    .{ .op = .ldx, .mode = .imm, .cycles = 2 },
    null,
    .{ .op = .ldy, .mode = .zp, .cycles = 3 },
    .{ .op = .lda, .mode = .zp, .cycles = 3 },
    .{ .op = .ldx, .mode = .zp, .cycles = 3 },
    null,
    .{ .op = .tay, .mode = .imp, .cycles = 2 },
    .{ .op = .lda, .mode = .imm, .cycles = 2 },
    .{ .op = .tax, .mode = .imp, .cycles = 2 },
    null,
    .{ .op = .ldy, .mode = .abs, .cycles = 4 },
    .{ .op = .lda, .mode = .abs, .cycles = 4 },
    .{ .op = .ldx, .mode = .abs, .cycles = 4 },
    null,

    // 0xb0
    .{ .op = .bcs, .mode = .rel, .cycles = 2 },
    .{ .op = .lda, .mode = .izy, .cycles = 5, .page_cycle = true },
    null,
    null,
    .{ .op = .ldy, .mode = .zpx, .cycles = 4 },
    .{ .op = .lda, .mode = .zpx, .cycles = 4 },
    .{ .op = .ldx, .mode = .zpy, .cycles = 4 },
    null,
    .{ .op = .clv, .mode = .imp, .cycles = 2 },
    .{ .op = .lda, .mode = .aby, .cycles = 4, .page_cycle = true },
    .{ .op = .tsx, .mode = .imp, .cycles = 2 },
    null,
    .{ .op = .ldy, .mode = .abx, .cycles = 4, .page_cycle = true },
    .{ .op = .lda, .mode = .abx, .cycles = 4, .page_cycle = true },
    .{ .op = .ldx, .mode = .aby, .cycles = 4, .page_cycle = true },
    null,

    // 0xc0
    .{ .op = .cpy, .mode = .imm, .cycles = 2 },
    .{ .op = .cmp, .mode = .izx, .cycles = 6 },
    null,
    null,
    .{ .op = .cpy, .mode = .zp, .cycles = 3 },
    .{ .op = .cmp, .mode = .zp, .cycles = 3 },
    .{ .op = .dec, .mode = .zp, .cycles = 5 },
    null,
    .{ .op = .iny, .mode = .imp, .cycles = 2 },
    .{ .op = .cmp, .mode = .imm, .cycles = 2 },
    .{ .op = .dex, .mode = .imp, .cycles = 2 },
    null,
    .{ .op = .cpy, .mode = .abs, .cycles = 4 },
    .{ .op = .cmp, .mode = .abs, .cycles = 4 },
    .{ .op = .dec, .mode = .abs, .cycles = 6 },
    null,

    // 0xd0
    .{ .op = .bne, .mode = .rel, .cycles = 2 },
    .{ .op = .cmp, .mode = .izy, .cycles = 5, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .cmp, .mode = .zpx, .cycles = 4 },
    .{ .op = .dec, .mode = .zpx, .cycles = 6 },
    null,
    .{ .op = .cld, .mode = .imp, .cycles = 2 },
    .{ .op = .cmp, .mode = .aby, .cycles = 4, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .cmp, .mode = .abx, .cycles = 4, .page_cycle = true },
    .{ .op = .dec, .mode = .abx, .cycles = 7 },
    null,

    // 0xe0
    .{ .op = .cpx, .mode = .imm, .cycles = 2 },
    .{ .op = .sbc, .mode = .izx, .cycles = 6 },
    null,
    null,
    .{ .op = .cpx, .mode = .zp, .cycles = 3 },
    .{ .op = .sbc, .mode = .zp, .cycles = 3 },
    .{ .op = .inc, .mode = .zp, .cycles = 5 },
    null,
    .{ .op = .inx, .mode = .imp, .cycles = 2 },
    .{ .op = .sbc, .mode = .imm, .cycles = 2 },
    .{ .op = .nop, .mode = .imp, .cycles = 2 },
    null,
    .{ .op = .cpx, .mode = .abs, .cycles = 4 },
    .{ .op = .sbc, .mode = .abs, .cycles = 4 },
    .{ .op = .inc, .mode = .abs, .cycles = 6 },
    null,

    // 0xf0
    .{ .op = .beq, .mode = .rel, .cycles = 2 },
    .{ .op = .sbc, .mode = .izy, .cycles = 5, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .sbc, .mode = .zpx, .cycles = 4 },
    .{ .op = .inc, .mode = .zpx, .cycles = 6 },
    null,
    .{ .op = .sed, .mode = .imp, .cycles = 2 },
    .{ .op = .sbc, .mode = .aby, .cycles = 4, .page_cycle = true },
    null,
    null,
    null,
    .{ .op = .sbc, .mode = .abx, .cycles = 4, .page_cycle = true },
    .{ .op = .inc, .mode = .abx, .cycles = 7 },
    null,
};
